.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2017-2021 Nicholas Guriev <guriev-ns@ya.ru>

.TH TELEGRAM-DESKTOP 1 "2021-08-04"

.SH NAME
\fBtelegram\-desktop\fR \- fast and secure messaging application

.SH SYNOPSIS
.SY telegram-desktop
.OP \-startintray
.OP \-debug
.OP \-scale INT
.OP \-workdir PATH
.OP \-\- URI
.YS
.SY telegram-desktop
.B \-autostart
.YS
.SY telegram-desktop
.B \-cleanup
.YS

.SH DESCRIPTION
This manual page documents how to run \fBTelegram Desktop\fR, official Telegram
client.

.SH OPTIONS
Although the program is primarily a GUI application, it understands various
command line arguments, some of them are described in the present document.
.TP
.B \-autostart
Apply automatic start. It works if only auto-starting is allowed in settings and
the app is not locked by a passcode. Telegram will start minimized in the system
tray if the corresponding checkbox has been set.
.TP
.B \-startintray
Do not show the main window, just start in the system tray. Useful for automatic
unconditional launching.
.TP
.B \-cleanup
Remove an autostart shortcut effectively disabling the feature then exit.
.TP
.B \-debug
Run in debug mode immediately. See full logs in working directory or in standard
location at \fB~/\.local/share/TelegramDesktop/DebugLogs\fR.
.TP
.B \-scale INT
Set initial interface scale factor. Possible values are measured in percents
from 75 up to 300 inclusive. The application remembers last used value.
.TP
.B \-workdir PATH
Change current working directory to specified path before start. All Telegram
data will be stored encrypted in this folder. It must exist before start. You
can pass this option to partition different app instances that run in parallel.
.TP
.I URI
Specify Telegram link in tg:// scheme. Double dash is mandatory. This is for
opening chats by \fBt.me\fR site.
.LP
There are also some other hidden options not intended for direct use.

.SH SEE ALSO
.UR https://github.com/telegramdesktop/tdesktop/wiki
Wiki on GitHub
.UE
