.\"                                      Hey, EMACS: -*- nroff -*-
.\"                                      Hey, vim: ft=nroff
.\" (C) Copyright 2017 Nicholas Guriev <guriev-ns@ya.ru>

.TH TELEGRAM-DESKTOP 1 "2017-06-07"

.SH NAME
\fBtelegram\-desktop\fR \- official telegram messaging application

.SH SYNOPSIS
.SY telegram-desktop
.OP \-startintray
.OP \-many
.OP \-debug
.OP \-\- URI
.YS

.SH DESCRIPTION
This manual page documents how to run \fBTelegram Desktop\fR, official Telegram
client.

.SH OPTIONS
The program understands various parameters, some of them are described in the
present document.
.TP
.B \-startintray
Do not show the main window, just start in the system tray. Useful for automatic
launching.
.TP
.B \-many
Allow multiple instances of the client at the same time.
.TP
.B \-debug
Run in debug mode immediately. See logs in
\fB~/\.local/share/TelegramDesktop/DebugLogs\fR.
.TP
.I URI
Specify Telegram URI. It is used for automatically opening chats by
.B t.me
site.

.SH ENVIRONMENT
.TP
.B HOME
User home directory where it stores downloaded files and configuration.

.SH SEE ALSO
.UR https://github.com/telegramdesktop/tdesktop/wiki
Wiki on GitHub
.UE
