Document: telegram-desktop
Title: Debian telegram-desktop Manual
Author: <insert document author here>
Abstract: This manual describes what telegram-desktop is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/telegram-desktop/telegram-desktop.sgml.gz

Format: postscript
Files: /usr/share/doc/telegram-desktop/telegram-desktop.ps.gz

Format: text
Files: /usr/share/doc/telegram-desktop/telegram-desktop.text.gz

Format: HTML
Index: /usr/share/doc/telegram-desktop/html/index.html
Files: /usr/share/doc/telegram-desktop/html/*.html
